version: "3.9"
services:
  app:
    platform: "linux/amd64"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_CLIENTVAR: "clientvar on build"
    working_dir: /app
    ports:
      - "3000:3000"
    image: t3-docker-demo-app
    environment:
       - NEXT_PUBLIC_CLIENTVAR_2="clientvar on runtime"
