import Head from "next/head";
import Link from "next/link";

import styles from "./index.module.css";
import { env } from "~/env.mjs";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.container}>
          <h2 className={styles.title}>
            Build :{" "}
            <span className={styles.pinkSpan}>{env.NEXT_PUBLIC_CLIENTVAR}</span>{" "}
          </h2>
          <h2 className={styles.title}>
            Runtime :{" "}
            <span className={styles.pinkSpan}>
              {env.NEXT_PUBLIC_CLIENTVAR_2}
            </span>{" "}
          </h2>
        </div>
      </main>
    </>
  );
}
